In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense , BatchNormalization , Dropout
from keras.callbacks import EarlyStopping

In [2]:
df = pd.read_csv(r"C:\datasets\SpotifyFeatures.csv")

In [3]:
df.drop(['artist_name' , 'track_name' , 'track_id'] , axis = 1 , inplace = True)

In [4]:
df.head(3)

,genre,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,0,0.611,0.389,99373,0.910,0.0,C#,0.346,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,1,0.246,0.590,137373,0.737,0.0,F#,0.151,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,3,0.952,0.663,170267,0.131,0.0,C,0.103,-13.879,Minor,0.0362,99.488,5/4,0.368

In [5]:
c = 0
for i in df['key'].unique():
    c += 1
print(c)

12

In [6]:
df.key.unique()

array(['C#', 'F#', 'C', 'F', 'G', 'E', 'D#', 'G#', 'D', 'A#', 'A', 'B'],
      dtype=object)

In [7]:
df.select_dtypes('int')

        popularity  duration_ms
0                0        99373
1                1       137373
2                3       170267
3                0       152427
4                4        82625
...            ...          ...
232720          39       326240
232721          38       282447
232722          47       166960
232723          44       222442
232724          35       323027

[232725 rows x 2 columns]

In [8]:
df.select_dtypes('float64')

,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence
0,0.61100,0.389,0.910,0.000000,0.3460,-1.828,0.0525,166.969,0.814
1,0.24600,0.590,0.737,0.000000,0.1510,-5.559,0.0868,174.003,0.816
2,0.95200,0.663,0.131,0.000000,0.1030,-13.879,0.0362,99.488,0.368
3,0.70300,0.240,0.326,0.000000,0.0985,-12.178,0.0395,171.758,0.227
4,0.95000,0.331,0.225,0.123000,0.2020,-21.150,0.0456,140.576,0.390
...,...,...,...,...,...,...,...,...,...
232720,0.00384,0.687,0.714,0.544000,0.0845,-10.626,0.0316,115.542,0.962
232721,0.03290,0.785,0.683,0.000880,0.2370,-6.944,0.0337,113.830,0.969
232722,0.90100,0.517,0.419,0.000000,0.0945,-8.282,0.1480,84.135,0.813
232723,0.26200,0.745,0.704,0.000000,0.3330,-7.137,0.1460,100.031,0.489
232724,0.09730,0.758,0.470,0.000049,0.0836,-6.708,0.0287,113.897,0.479

In [9]:
df.head(4)

,genre,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,0,0.611,0.389,99373,0.910,0.0,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,1,0.246,0.590,137373,0.737,0.0,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,3,0.952,0.663,170267,0.131,0.0,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,0,0.703,0.240,152427,0.326,0.0,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227